{
 "title": "Subarashii",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "db.users.aggregate({\n  $count: \"users\"\n})"
    }
   ]
  },
  {
   "title": "Nombre d'utilisateurs banni",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "db.users.aggregate([\n{\n  \"$match\": {\n    \"banned\": true\n  }\n},\n{\n  \"$count\": \"users\"\n}\n])"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "db.lists.aggregate([\n  { $group: { _id: \"$owner\", somme: { $count: {} } } },\n  { $group: { _id: null , moyenne: { $avg: \"$somme\" } } }\n])"
    }
   ]
  },
  {
   "title": "Comments created per days",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "db.comments.aggregate(\n  { \n    $group: { \n      _id: { $dateToString: { format: \"%Y-%m-%d\", date: \"$created_at\"} },\n      comments: { $sum: 1 } \n    } \n  }\n)"
    }
   ]
  }
 ]
}