# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Yarn
      run: npm install
    - name: Install
      uses: cypress-io/github-action@v2
      with:
        runTests: false
    - name: Build the source code
      uses: actions/upload-artifact@v2
      with:
        name: build
        if-no-files-found: error
        path: build
    - name: Download Cypress artifacts
      uses: actions/download-artifact@v2
      with:
        name: build
        path: build