name: Node.js CI
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install-command: npm i --force
          working-directory: app
          browser: chrome
          config: pageLoadTimeout=100000,baseUrl=https://subarashii-front-end-audit-v2-mido57iq6-antobrines.vercel.app/login

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: app/cypress/screenshots

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: app/cypress/videos
